# DAV Assignment 1
## Name: Piyush Khokale
### Class: A-A2
### Roll No: 17

In [22]:
import pandas as pd
import xml.etree.ElementTree as ET
import json

# 1. Data Collection

## Txt File

In [23]:
with open("data/students.txt","w") as f:
    f.write("ID Name Age\n")
    f.write("1 Saptanshu 22\n")
    f.write("2 Hardik 21\n")
    f.write("3 Saumya 22")
    f.write("4 Piyush 22")

## JSON File

In [24]:
students = [
    {"id": 1, "name": "Saptanshu", "age": 22},
    {"id": 2, "name": "Hardik", "age": 21},
    {"id": 3, "name": "Saumya", "age": 22},
    {"id": 4, "name": "Piyush", "age": 22}
]

with open("data/students.json","w") as f:
    json.dump(students, f, indent=4)

## XML File

In [25]:
root = ET.Element("students")

for student in students:
    s = ET.SubElement(root, "student")
    ET.SubElement(s, "id").text = str(student["id"])
    ET.SubElement(s, "name").text = student["name"]
    ET.SubElement(s, "age").text = str(student["age"])

tree = ET.ElementTree(root)
tree.write("data/students.xml")

# 2. CSV Data collection

In [26]:
data={
        "ID" :[1,2,3,4],
        "Name": ["Saptanshu","Hardik","Saumya","Piyush"],
        "Age":[22,21,22,22]
        }
df=pd.DataFrame(data)

In [27]:
df.to_csv("data/students.csv",index=False)

In [28]:
df1=pd.read_csv("data/students.csv")
print("\nHead")
print(df1)
print("\nTail")
print(df1)
print("\nInfo")
df1.info()
print("\nDescribe")
df1.describe()

Head
   ID       Name  Age
0   1  Saptanshu   22
1   2     Hardik   21
2   3     Saumya   22
3   4     Piyush   22

Tail
   ID       Name  Age
0   1  Saptanshu   22
1   2     Hardik   21
2   3     Saumya   22
3   4     Piyush   22

Info
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   Name    4 non-null      str
 2   Age     4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

Describe

             ID    Age
count  4.000000   4.00
mean   2.500000  21.75
std    1.290994   0.50
min    1.000000  21.00
25%    1.750000  21.75
50%    2.500000  22.00
75%    3.250000  22.00
max    4.000000  22.00

# 3. Data Analysis

In [29]:
customers = pd.DataFrame({
    "CustomerID": [101, 102, 103, 104],
    "Name": ["Saptanshu", "Hardik", None, "Saumya"],
    "Age": [22, 21, None, 22],
    "City": ["Delhi", "Mumbai", "Delhi", None]
})

In [9]:
orders = pd.DataFrame({
    "OrderID": [1, 2, 3, 4],
    "CustomerID": [101, 102, 101, 104],
    "Amount": [500, 700, None, 450]
})

In [20]:
print("\nCustomers Data")
print(customers)

print("\nOrders Data")
print(orders)

print("\nCustomers Info")
customers.info()

print("\nOrders Info")
orders.info()

Customers Data
   CustomerID       Name        Age     City
0         101  Saptanshu  22.000000    Delhi
1         102     Hardik  21.000000   Mumbai
2         103    Unknown  21.666667    Delhi
3         104     Saumya  22.000000  Unknown

Orders Data
   OrderID  CustomerID  Amount
0        1         101   500.0
1        2         102   700.0
2        3         101   550.0
3        4         104   450.0

Customers Info
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  4 non-null      int64
 1   Name        4 non-null      str
 2   Age         4 non-null      float64
 3   City        4 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes

Orders Info
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     4 non-null      int64
 1   CustomerID  4 non-null      int64
 2   Amount      4 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 228.0 bytes

In [11]:
customers["Name"] = customers["Name"].fillna("Unknown")

In [12]:
customers["Age"] = customers["Age"].fillna(customers["Age"].mean())

In [13]:
customers["City"] = customers["City"].fillna("Unknown")

In [14]:
orders["Amount"] = orders["Amount"].fillna(orders["Amount"].mean())

In [15]:
customers = customers.drop_duplicates()
orders = orders.drop_duplicates()

In [16]:
merged = pd.merge(customers, orders, on="CustomerID")

In [19]:
print("\nMerged Data")
print(merged)

print("\nMerged Info")
merged.info()

print("\nMerged Describe")
merged.describe()

Merged Data
   CustomerID       Name   Age     City  OrderID  Amount
0         101  Saptanshu  22.0    Delhi        1   500.0
1         101  Saptanshu  22.0    Delhi        3   550.0
2         104     Saumya  22.0  Unknown        4   450.0
3         102     Hardik  21.0   Mumbai        2   700.0

Merged Info
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  4 non-null      int64
 1   Name        4 non-null      str
 2   Age         4 non-null      float64
 3   City        4 non-null      str
 4   OrderID     4 non-null      int64
 5   Amount      4 non-null      float64
dtypes: float64(2), int64(2), str(2)
memory usage: 324.0 bytes

Merged Describe

       CustomerID    Age   OrderID      Amount
count    4.000000   4.00  4.000000    4.000000
mean   102.000000  21.75  2.500000  550.000000
std      1.414214   0.50  1.290994  108.012345
min    101.000000  21.00  1.000000  450.000000
25%    101.000000  21.75  1.750000  487.500000
50%    101.500000  22.00  2.500000  525.000000
75%    102.500000  22.00  3.250000  587.500000
max    104.000000  22.00  4.000000  700.000000